#!/bin/sh
#
# chkconfig: 345 95 5
# description: Control the OpenAM Tomcat Server
#
# Set the path to the OpenDJ instance to manage
# Tomcat OpenAM auto-start
#
# description: Auto-starts tomcat
# start tomcat with user: ssouser
# pidfile: /var/run/tomcat.pid


export JAVA_HOME=/opt/isv/iam/jdk1.8.0_102

INSTALL_ROOT="/opt/isv/iam/apache-tomcat-7.0.69"
export INSTALL_ROOT

cd ${INSTALL_ROOT}

case $1 in
start)
        # uncomment the following line in production since the config stores are on the same server
        #start on started opendj
        /bin/su ssouser -c "${INSTALL_ROOT}/bin/startup.sh"
        ;;
stop)
        /bin/su ssouser -c "${INSTALL_ROOT}/bin/shutdown.sh"
        ;;
restart)
        /bin/su ssouser -c "${INSTALL_ROOT}/bin/shutdown.sh"
        /bin/su ssouser -c "${INSTALL_ROOT}/bin/startup.sh"
        ;;
esac
exit 0
